---

sudo: false

dist: xenial # required for Python >= 3.7
language: python
python:
  - 3.7
cache: pip

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install: true

before_script:
  - pip3 install tox

script: tox

notifications:
  email: false

env:
  TOXENV=py37
  DB_HOST=localhost
  DB_USER=Travis
  DB_PASS=
  DB_PORT=3306
  DB_NAME=test