---

sudo: false

language: python
cache: pip

before_script:
  - pip install tox

script: tox

install: true

notifications:
  email: false

matrix:
  fast_finish: true
  include:

    - python: "3.7"
      env: TOXENV=py37