---

sudo: false

dist: xenial
language: python
python:
  - 3.6
cache: pip

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install: true

before_script:
  - pip3 install tox

script: tox

notifications:
  email: false

env:
  TOXENV=py36
  DB_HOST=localhost
  DB_USER=Travis
  DB_PASS=
  DB_PORT=3306
  DB_NAME=test
