version: '3'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
    ports: 
      - "3306"

  app:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db